# Generated by Django 5.0.6 on 2024-07-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_form_see_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
