# Generated by Django 5.0.6 on 2024-07-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_form_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='time',
        ),
    ]
